(function(){function e(a){this.f=this.canvas=a.canvas||document.createElement("canvas");this.f.width=a.width||800;this.f.height=a.height||600;this.b=a.width;this.d=a.height;this.o=this.f.getContext("2d");this.scale=a.scale||1;this.L=a.L||!1;this.onclick=a.onclick;this.x=a.x||0;this.y=a.y||0;this.k=new p;this.U=function(){var a,c,d;this.b/this.d<this.a.width/this.a.height&&this.L?(a=this.d/this.a.height,c=(this.b-this.a.width*a)/2,d=0):(a=this.b/this.a.width,c=0,d=(this.d-this.a.height*a)/2);this.i(a,
c,d)}.bind(this);this.Z()}function p(a,b,c,d,m,e){this.B=null;a&&b&&c&&this.l(a,b,c,d,m,e)}(function(){for(var a=0,b=["webkit","moz"],c=0;c<b.length&&!window.requestAnimationFrame;++c)window.requestAnimationFrame=window[b[c]+"RequestAnimationFrame"],window.cancelAnimationFrame=window[b[c]+"CancelAnimationFrame"]||window[b[c]+"CancelRequestAnimationFrame"];window.requestAnimationFrame||(window.requestAnimationFrame=function(b){var c=(new Date).getTime(),e=Math.max(0,30-(c-a)),k=window.setTimeout(function(){b(c+
e)},e);a=c+e;return k});window.cancelAnimationFrame||(window.cancelAnimationFrame=function(a){clearTimeout(a)})})();e.prototype={s:3,n:null,q:null,v:null,I:null,index:-1,g:null,select:function(a){if(!(a==this.index||0>a||a>=this.g.length)){this.index=a;var b,c,d;b=this.g[a];a<this.g.length-1&&(d=this.g[a+1]);0<a&&(c=this.g[a-1]);this.X(b);this.H(c);this.G(d)}},next:function(){this.e&&(this.c=this.a,this.w=this.y,this.h=this.scale,this.index++,this.a=this.e,this.y=this.t,this.x=this.c.width*this.h+
this.x,this.scale=this.j,this.index<this.g.length-1?this.G(this.g[this.index+1]):this.e=null,this.k.l({x:this.x},{x:0},function(a){this.i(this.scale,a.x,this.y)}.bind(this),200,null,function(){this.H(this.g[this.index-1])}.bind(this)))},Y:function(){this.c&&(this.e=this.a,this.t=this.y,this.j=this.scale,this.index--,this.a=this.c,this.y=this.w,this.x=this.x-this.c.width*this.h-this.b/10,this.scale=this.h,0<this.index?this.H(this.g[this.index-1]):this.c=null,this.k.l({x:this.x},{x:0},function(a){this.i(this.scale,
a.x,this.y)}.bind(this),200,null,function(){this.G(this.g[this.index+1])}.bind(this)))},F:function(a,b){if("string"==typeof a)b.src=a;else if(a.V||!a.small)b.src=a.src;else{b.src=a.small;var c=new Image;c.onload=function(){b.src=a.src;a.V=!0};c.src=a.src}},X:function(a){this.a=new Image;this.a.onload=this.U;this.F(a,this.a)},H:function(a){a?(this.h=this.w=this.N=null,this.c=new Image,this.c.onload=function(){this.c&&(this.h=this.b/this.c.width,this.w=this.c.height*this.h<this.d?(this.d-this.c.height*
this.h)/2:0)}.bind(this),this.F(a,this.c)):(this.c&&(this.c.onload=null),this.c=null)},G:function(a){a?(this.j=this.t=this.M=null,this.e=new Image,this.e.onload=function(){this.e&&(this.j=this.b/this.e.width,this.t=this.e.height*this.j<this.d?(this.d-this.e.height*this.j)/2:0)}.bind(this),this.F(a,this.e)):(this.e&&(this.e.onload=null),this.e=null)},Z:function(){var a=null,b=null,c=null,d=null,e=null,f=null,k=null,q=null,t,u,l="mousedown",g="mousemove",p="mouseup";void 0!==document.ontouchstart&&
(l="touchstart",g="touchmove",p="touchend");this.f.addEventListener(l,function(h){this.$=new Date;this.O=!1;this.k.clear();h.preventDefault();q=this.scale;h.targetTouches||(h.targetTouches=[{pageX:h.pageX,pageY:h.pageY}]);a=h.targetTouches[0].pageX-this.f.getBoundingClientRect().left;b=h.targetTouches[0].pageY-this.f.getBoundingClientRect().top;2==h.targetTouches.length?(c=h.targetTouches[1].pageX-this.f.getBoundingClientRect().left,d=h.targetTouches[1].pageY-this.f.getBoundingClientRect().top,e=
a+(c-a)/2,f=b+(d-b)/2,k=Math.sqrt(Math.pow(c-a,2)+Math.pow(d-b,2))):(e=a,f=b,k=0);t=e-this.x;u=f-this.y;this.n=h.targetTouches[0].pageX;this.q=h.targetTouches[0].pageY;this.a.width*this.scale<=this.b&&(this.D=this.C=!0)}.bind(this),!1);var r=null,s=null,v=null,w=null,x=null,y=null,z=null;this.f.addEventListener(g,function(a){a.preventDefault();if(null!==k){a.targetTouches||(a.targetTouches=[{pageX:a.pageX,pageY:a.pageY}]);this.O=!0;var b=this.scale,c,d;r=a.targetTouches[0].pageX-this.f.getBoundingClientRect().left;
s=a.targetTouches[0].pageY-this.f.getBoundingClientRect().top;2==a.targetTouches.length?(v=a.targetTouches[1].pageX-this.f.getBoundingClientRect().left,w=a.targetTouches[1].pageY-this.f.getBoundingClientRect().top,x=r+(v-r)/2,y=s+(w-s)/2,z=Math.sqrt(Math.pow(v-r,2)+Math.pow(w-s,2)),b=q*(z/k||1)):(x=r,y=s,z=0);b*this.a.width<this.b?b-=.7*(b-this.b/this.a.width):b*this.a.width>this.b*this.s&&(b-=.7*(b-this.b*this.s/this.a.width));c=x-t/q*b;d=y-u/q*b;this.v=this.n;this.I=this.q;this.n=a.targetTouches[0].pageX;
this.q=a.targetTouches[0].pageY;a=this.u(b,c,d);a.x!=c&&(!(0<c)||this.c&&this.C?!(0>c)||this.e&&this.D||(c=a.x+.3*(c-a.x)):c=a.x+.3*(c-a.x));a.y!=d&&(d=a.y+.3*(d-a.y));this.i(b,c,d)}}.bind(this),!1);this.f.addEventListener(p,function(a){a.preventDefault();if(0==this.O&&1E3>new Date-this.$&&"function"==typeof this.onclick)this.onclick(this.index);a.targetTouches||(a.targetTouches=[]);1==a.targetTouches.length?(d=c=null,e=a.targetTouches[0].pageX-this.f.getBoundingClientRect().left,f=a.targetTouches[0].pageY-
this.f.getBoundingClientRect().left,t=e-this.x,u=f-this.y,q=this.scale,k=0):(k=f=e=null,this.aa(a))}.bind(this),!1)},aa:function(){var a={},b={};if(this.scale*this.a.width<this.b)a.scale=this.scale,b.scale=this.b/this.a.width,a.x=this.x,b.x=0,a.y=this.y,b.y=b.scale/a.scale*(this.y-this.d/2)+this.d/2,0<b.y&&(b.y=0),this.k.l(a,b,function(a){this.i(a.scale,a.x,a.y)}.bind(this),300);else if(this.scale*this.a.width>this.b*this.s)a.scale=this.scale,b.scale=this.b/this.a.width*this.s,a.x=this.x,b.x=b.scale/
a.scale*(this.x-this.b/2)+this.b/2,a.y=this.y,b.y=b.scale/a.scale*(this.y-this.d/2)+this.d/2,b=this.u(b.scale,b.x,b.y),this.k.l(a,b,function(a){this.i(a.scale,a.x,a.y)}.bind(this),300);else if(null!==this.n&&null!==this.v){var c=this.n-this.v,d=this.q-this.I;a.x=this.x;a.y=this.y;var e=this.b/3,f=this.b/50,k=this.u(this.scale,a.x,a.y);this.a.width*this.scale>=this.b&&(this.D=this.C=!1,0<=this.x&&(this.C=!0),this.x<=-Math.floor(this.a.width*this.scale-this.b)&&(this.D=!0));if(k.x!=a.x&&(Math.abs(c)>
f&&this.a.width*this.scale<=this.b&&this.a.height*this.scale<=this.d||Math.abs(a.x-k.x)>e)){if(0<a.x&&this.c){this.Y();return}if(0>a.x&&this.e){this.next();return}}b.x=this.x+5*c;b.y=this.y+5*d;b=this.u(this.scale,b.x,b.y);this.k.l(a,b,function(a){this.i(this.scale,a.x,a.y)}.bind(this),300,null)}this.I=this.v=this.q=this.n=null},u:function(a,b,c){var d={};d.scale=a;d.x=b;d.y=c;0<b?d.x=0:b<-(this.a.width*a-this.b)&&(d.x=-this.a.width*a+this.b);this.a.height*a<this.d?d.y=(this.d-this.a.height*a)/2:
0<c?d.y=0:c<-(this.a.height*a-this.d)&&(d.y=-this.a.height*a+this.d);return d},i:function(a,b,c){this.a.height*a<this.d&&(c=(this.d-this.a.height*a)/2);this.scale=a;this.x=b;this.y=c;this.o.fillStyle="#000";this.o.fillRect(0,0,this.b,this.d);this.o.drawImage(this.a,b,c,a*this.a.width,this.scale*this.a.height);this.x>this.b/10&&this.c&&(this.N=-this.c.width*this.h+this.x-this.b/10,this.o.drawImage(this.c,this.N,this.w,this.h*this.c.width,this.h*this.c.height));this.x<-(this.a.width*this.scale-this.b)-
this.b/10&&this.e&&(this.M=this.x+this.a.width*this.scale+this.b/10,this.o.drawImage(this.e,this.M,this.t,this.j*this.e.width,this.j*this.e.height))}};e.prototype.setImages=function(a,b){if(a.length){this.g=[];for(var c,d=0;d<a.length;d++)c="string"===typeof a[d]?{src:a[d]}:{src:a[d].src,small:a[d].small},this.g.push(c);this.index=-1;this.select(parseInt(b)||0)}};p.prototype={l:function(a,b,c,d,e,f){a&&b&&"function"==typeof c&&(this.A=a,this.p=b,this.K=c,this.P=d||3E3,this.m=f,this.T="function"===
typeof e?e:"easeInOut"==e?this.r.R:"easeIn"==e?this.r.Q:"linear"==e?this.r.W:this.r.S,clearTimeout(this.B),this.startTime=new Date,this.J())},J:function(){var a=this,b={},c=new Date-this.startTime;for(n in this.A)"number"==typeof this.A[n]&&"number"==typeof this.p[n]&&(b[n]=this.T(c,this.A[n],this.p[n]-this.A[n],this.P));c>=this.P?(this.K(this.p),"function"==typeof this.m&&(this.m(this.p),this.m=null)):(this.K(b),this.B=requestAnimationFrame(function(){a.J()}))},clear:function(){cancelAnimationFrame(this.B);
"function"==typeof this.m&&(this.m(this.p),this.m=null)},r:{Q:function(a,b,c,d){return c*(a/=d)*a+b},S:function(a,b,c,d){return-c*(a/=d)*(a-2)+b},R:function(a,b,c,d){return 1>(a/=d/2)?c/2*a*a+b:-c/2*(a*(a-2)-1)+b},W:function(a,b,c,d){return c*a/d+b}}};window.TouchPhotos=e})();
(function(){function e(a,b){return(b||document).querySelector(a)}function p(a,b){var c=0,d=0,e=a;try{for(;null!=e&&e!=document.body&&e!=document.documentElement&&e!=b;)c+=e.offsetLeft,d+=e.offsetTop,e=e.offsetParent}catch(g){}return{left:c,top:d}}function a(a){b||(document.getElementById("shareAlert").innerHTML='<div class="othersShare">\u5206\u4eab\uff1a<a href="javascript:void(0)" onclick="shareSina()"><img src="/microblog-v3/2014subject/1216_oneword/images/sina.png"></a> <a href="javascript:void(0)" onclick="sharePeople()"><img src="/microblog-v3/2014subject/1216_oneword/images/people.png"></a> <a href="javascript:void(0)" onclick="shareTencent()"><img src="/microblog-v3/2014subject/1216_oneword/images/tencent.png"></a></div>');
e("#shareAlert").style.display="block";setTimeout(function(){e("#shareAlert").style.display="none"},5E3)}navigator.userAgent.match(/ OS (\d+).*? Mac OS/);navigator.userAgent.indexOf("NetType/WIFI");var b=-1!==navigator.userAgent.indexOf("Messenger"),c=navigator.userAgent.match(/(?:Windows Phone|SymbianOS|Android|iPad|iPod|iPhone)/),c=c?c[0]:!1;if(b&&"t.people.com.cn"!=location.host)location.href="http://t.people.com.cn/h5/paiyuebing";else{var d=document.body.clientWidth,m=document.body.clientHeight,
d=640<d?640:d,m=1008<m?1008:m,f=d/640;c?640>d&&(document.body.style["font-size"]=32*f+"px"):(c=document.documentElement.clientHeight/504*16,d=Math.round(document.documentElement.clientHeight/504*320),document.body.style["font-size"]=c+"px",document.body.style.width=d+"px");({page:1,imgDomain:"http://i0.peopleurl.cn/",init:function(){var b=this,c=location.href.match(/\/(\d+)($|\?)/)||location.href.match(/id=(\d+)($|\&)/);if(c){this.dataId=c=c[1];var e=new XMLHttpRequest;e.onreadystatechange=function(){if(4==
e.readyState&&200==e.status){var d=e.responseText;window.localStorage&&localStorage.ybId==c&&(a(),localStorage.ybId="");d=eval("("+d+")");b.preview(d)}else 4==e.readyState&&alert("\u7f51\u7edc\u5fd9\uff0c\u8bf7\u7a0d\u540e\u518d\u8bd5\uff01code:"+e.status)};e.ontimeout=function(a){alert("\u7f51\u7edc\u4e0d\u7ed9\u529b\uff0c\u8bf7\u5728\u8f83\u597d\u7684\u7f51\u7edc\u73af\u5883\u4e2d\u518d\u8bd5\uff01")};e.open("GET","/getYbRecord.action?contentId="+c,!0);e.send(null);this.touchPhotos=new TouchPhotos({canvas:document.getElementById("photosCanvas"),
width:d,height:m,onclick:function(){b.touchPhotos.canvas.className="canvasHide";setTimeout(function(){b.touchPhotos.canvas.className=""},300)}})}else alert("\u8bf7\u6307\u5b9aid")},preview:function(b){var c=this;if(1==b.result&&b.imageList&&b.imageList.length){for(var d=[],f=!0,l="<ul>",g=0;g<b.imageList.length;g++)2!=b.imageList[g].status&&(f=!1),l+='<li><img src="'+this.imgDomain+b.imageList[g].smallPicName+'" data-src="'+this.imgDomain+b.imageList[g].picName+'" data-index="'+g+'" /></li>',d.push({src:this.imgDomain+
b.imageList[g].picName,small:this.imgDomain+b.imageList[g].smallPicName});l+="</ul>";f||window.localStorage&&localStorage.myYbIdList&&localStorage.myYbIdList.match(new RegExp("(^|_)"+this.dataId+"(_|$)"))||(l='<div class="errorTxt">\u56fe\u7247\u8fd8\u5728\u8def\u4e0a\uff0c\u9a6c\u4e0a\u5c31\u5230^_^</div>',window.onscroll=null,this.toplist=!0,e("#otherBox").style.display="none");e(".userPhone").innerHTML="<span>"+b.mobile+"</span> \u7684\u4f5c\u54c1";e("#userPhotos").innerHTML=l;e(".voteBtn").innerHTML=
"\u6295\u7968(\u5df2\u6709"+b.dzCount+"\u7968)";b=document.querySelectorAll("#userPhotos img");c=this;cFN=function(){c.touchPhotos.setImages(d,this.getAttribute("data-index"));c.touchPhotos.canvas.className="canvasShow"};for(g=0;g<b.length;g++)b[g].onclick=cFN;e("#shareBtn").onclick=function(){a()};e(".voteBtn").onclick=function(){this.vote()}.bind(this);var m=p(e("#toplist"));window.onscroll=function(){window.pageYOffset+document.body.clientHeight>=m.top&&c.loadTopList()}}else e("#userPhotos").innerHTML=
'<div class="errorTxt">\u256e(\u256f_\u2570)\u256d<br>\u7167\u7247\u62cd\u7684\u4e0d\u591f\u597d\uff0c\u7ee7\u7eed\u52aa\u529b\uff01</div>',window.onscroll=null,this.toplist=!0,e("#otherBox").style.display="none",e(".voteBtn").style.display="none"},toplist:!1,loadTopList:function(){if(!this.toplist){var a=this;window.onscroll=null;this.toplist=!0;var b=new XMLHttpRequest;b.onreadystatechange=function(){if(4==b.readyState&&200==b.status){var c=eval("("+b.responseText+")");if(c&&1==c.result){for(var d=
"<ul>",f=0;f<c.imageList.length;f++)d+='<li><a href="/h5/paiyuebing/'+c.imageList[f].contentId+'"><img src="'+a.imgDomain+c.imageList[f].smallPicName+'" /></a></li>';d+="</ul>";e("#toplist").innerHTML=d;c.total&&(e("#toplistTit").innerHTML="\u6700\u65b0\u4e0a\u4f20\uff1a(\u5171"+c.total+"\u7ec4)")}else e("#toplist").innerHTML="\u8f7d\u5165\u5931\u8d25"}};b.ontimeout=function(a){e("#toplist").innerHTML="\u7f51\u7edc\u8d85\u65f6"};b.open("GET","/getYbNewImageList.action?contentId="+this.dataId,!0);
b.setRequestHeader("Content-Type","application/x-www-form-urlencoded");b.send()}},vote:function(){var a=this;if(window.localStorage&&localStorage.ybVoteList&&localStorage.ybVoteList.match(new RegExp("(^|_)"+this.dataId+"(_|$)")))alert("\u4e0d\u80fd\u91cd\u590d\u6295\u7968\uff01 \u8fd8\u662f\u5206\u4eab\u5230\u670b\u53cb\u5708\u5e2e\u6211\u62c9\u62c9\u7968\u5427\uff01^_^");else{var b=new XMLHttpRequest;b.onreadystatechange=function(){if(4==b.readyState&&200==b.status){var c=eval("("+b.responseText+
")");c&&0<c.result&&(window.localStorage&&(localStorage.ybVoteList=localStorage.ybVoteList+"_"+a.dataId),e(".voteBtn").innerHTML="\u6295\u7968(\u5df2\u6709"+c.result+"\u7968)",alert("\u611f\u8c22\u60a8\u4e3a\u6211\u6295\u7968, \u987a\u624b\u5e2e\u6211\u5206\u4eab\u5230\u670b\u53cb\u5708\u62c9\u62c9\u7968\u5427\uff01^_^"))}};b.ontimeout=function(a){alert("\u7f51\u7edc\u8d85\u65f6\uff0c\u8bf7\u7a0d\u540e\u518d\u8bd5\uff01")};b.open("POST","/addYbDianzan.action",!0);b.setRequestHeader("Content-Type",
"application/x-www-form-urlencoded");b.send("contentId="+this.dataId)}}}).init()}})();
